extends: google
globals:
  goog: false
env:
  browser: true
plugins:
  - mocha
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars:
    - error

  require-jsdoc: off
  valid-jsdoc: off

  prefer-const: error
